### PR TITLE
Updated the about section

### PR DESCRIPTION
**Pull request by annu12340**
I have corrected a few typos in about.md and made some changes in the UI of the about section
I have also made the page responsive

dynamicLearning

### CODE REVIEW

**Comment by JithinKS97** [comment]
@annu12340 Hi Annu thanks for the pull request.

Regarding the changes in About page, [This is the initial design](https://photos.google.com/u/2/photo/AF1QipOmk6XUCeH1mfNRKCXdXK1hcVBAkFrESgzTccrf) that we had for the page. Before we bring any noticeable changes to it, I think we can also get the suggestion of my friend who has done the design works. So will you be able to hold on those changes alone? I can come back to you with the design suggestions for the reduced screen page. I'm fine with the rest of the changes.

**Comment by annu12340** [comment]
> @annu12340 Hi Annu thanks for the pull request.
> 
> Regarding the changes in About page, [This is the initial design](https://photos.google.com/u/2/photo/AF1QipOmk6XUCeH1mfNRKCXdXK1hcVBAkFrESgzTccrf) that we had for the page. Before we bring any noticeable changes to it, I think we can also get the suggestion of my friend who has done the design works. So will you be able to hold on those changes alone? I can come back to you with the design suggestions for the reduced screen page. I'm fine with the rest of the changes.

😃 Yeah sure

**Comment by JithinKS97** [comment]
@annu12340 Sorry for not merging this soon. I've ran your branch in local and I found some issues. Can you look at them?
1. For now, we can remove the green background above (Just comment out the code, we can consider it later)
2. The image of the programmer appears to be vertically squeezed, maybe you can restore it back to the size it was before.
3. https://www.photobox.co.uk/my/photo/full?photo_id=503335228070 - The label below the logo seems to be mixed up with the description.
If you can update the PR with the fix, I can merge it immediately.

**Comment by annu12340** [comment]
> @annu12340 Sorry for not merging this soon. I've ran your branch in local and I found some issues. Can you look at them?
> 
> 1. For now, we can remove the green background above (Just comment out the code, we can consider it later)
> 2. The image of the programmer appears to be vertically squeezed, maybe you can restore it back to the size it was before.
> 3. https://www.photobox.co.uk/my/photo/full?photo_id=503335228070 - The label below the logo seems to be mixed up with the description.
>    If you can update the PR with the fix, I can merge it immediately.

I have made the suggested changes

**Comment by JithinKS97** [comment]
@annu12340 Thanks for this change. Merging to dev.

**Review by JithinKS97 — APPROVED** [review]

**Pull request merged**
